import { css } from "lit";

export const styles = css`
  :host { display:block; --ink:var(--primary-text-color,#18352e); --muted:var(--secondary-text-color,#677870); --surface:var(--card-background-color,#fff); --soft:#f3f7f4; --accent:#157456; --line:#dce6df; color:var(--ink); font-family:var(--paper-font-body1_-_font-family,system-ui,-apple-system,sans-serif); }
  * { box-sizing:border-box; } button,input,select,textarea { font:inherit; } button,input,select,textarea,a { -webkit-tap-highlight-color:transparent; }
  .card { border:1px solid var(--line); border-radius:20px; overflow:hidden; background:var(--surface); box-shadow:0 8px 28px #19352d08; }
  header { padding:23px 26px 19px; display:flex; justify-content:space-between; align-items:center; gap:12px; border-bottom:1px solid var(--line); }
  .brand { display:flex; align-items:center; gap:12px; } .brand-icon { width:43px; height:43px; display:grid; place-items:center; border-radius:13px; background:#e8f3ed; color:var(--accent); }
  .brand-icon svg { width:24px; height:24px; } h1 { font-size:20px; font-weight:650; margin:0 0 4px; letter-spacing:-.4px; } h2 { font-size:16px; margin:0 0 7px; } h3 { font-size:14px; margin:0 0 8px; }
  p { line-height:1.55; margin:7px 0; } .muted,.subline { color:var(--muted); font-size:12px; } .subline { margin:0; } .badge { background:#edf6f0; color:#39705c; font-size:11px; font-weight:600; padding:5px 9px; border-radius:20px; white-space:nowrap; }
  button,.file-button { display:inline-flex; align-items:center; justify-content:center; gap:7px; min-height:39px; padding:9px 13px; border:1px solid var(--line); border-radius:9px; background:var(--surface); color:var(--ink); font-weight:600; font-size:12px; cursor:pointer; text-decoration:none; }
  button:hover,.file-button:hover { background:var(--soft); border-color:#a9bfb0; } button.primary { background:var(--accent); color:white; border-color:var(--accent); } button.primary:hover { background:#105c43; }
  button:disabled,.file-button.disabled { opacity:.5; cursor:not-allowed; } button.danger { color:#a04032; } button.icon { padding:7px 10px; min-height:34px; } button svg,.file-button svg { height:16px; width:16px; flex:none; }
  button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible,.file-button:focus-within,a:focus-visible { outline:3px solid #5fa891; outline-offset:2px; } .file-button { position:relative; overflow:hidden; } .file-button input[type=file] { position:absolute; inset:0; width:100%; height:100%; opacity:0; cursor:pointer; }
  .toolbar { padding:14px 26px; display:flex; align-items:center; justify-content:space-between; gap:12px; } .actions { display:flex; flex-wrap:wrap; gap:8px; } .floor-tabs { display:flex; gap:5px; overflow-x:auto; } .floor-tabs button { flex:none; border-color:transparent; color:var(--muted); background:transparent; }
  .floor-tabs button.active { color:var(--accent); background:#eaf4ee; } .notice { color:#254a3b; padding:12px 16px; font-size:12px; line-height:1.5; border-radius:10px; background:#edf6f0; border:1px solid #d4e9dc; margin:0 26px 15px; }
  .notice.warning { color:#775c24; background:#fff8e8; border-color:#eddfbc; } .notice.error { color:#983d2f; background:#fff2ef; border-color:#edc6bd; } .notice ul { margin:6px 0 0; padding-left:20px; } .notice p { margin:2px 0; }
  .content { display:grid; grid-template-columns:minmax(0,1fr) 285px; border-top:1px solid var(--line); } .plan-area { min-width:0; padding:20px; background:#f3f6f2; } .plan-heading { display:flex; justify-content:space-between; align-items:center; margin-bottom:14px; gap:12px; }
  .plan-heading strong { font-size:12px; font-weight:600; } .plan-frame { width:100%; background:white; border:1px solid #dce4dc; border-radius:12px; overflow:hidden; box-shadow:0 3px 10px #243b2610; }
  .plan-svg { display:block; width:100%; height:auto; } .plan-svg.editing { touch-action:none; } .room-shape { fill:#21906d1b; stroke:#158665; stroke-width:1.8; vector-effect:non-scaling-stroke; cursor:pointer; transition:fill .12s; }
  .room-shape:hover,.room-shape:focus { fill:#21906d45; outline:none; stroke-width:3; } .room-shape.selected { fill:#13916445; stroke:#106e50; stroke-width:2.5; } .room-label { font-family:inherit; font-size:18px; fill:#144b38; text-anchor:middle; dominant-baseline:middle; pointer-events:none; } .label-group { pointer-events:none; } .label-bg { fill:#f9fffa; stroke:#b8d5c6; stroke-width:1; }
  .vertex { fill:white; stroke:#107453; stroke-width:2; vector-effect:non-scaling-stroke; cursor:grab; } .vertex:active { cursor:grabbing; } .legend { display:flex; flex-wrap:wrap; gap:15px; color:var(--muted); font-size:11px; margin:13px 0 0; } .legend span { display:flex; align-items:center; gap:6px; } .dot { height:8px; width:8px; border-radius:3px; background:#1b8a6840; border:1px solid #208b67; } .dot.selected { background:#18875e8a; }
  aside { border-left:1px solid var(--line); padding:21px 19px; } .eyebrow { font-size:10px; color:var(--muted); text-transform:uppercase; letter-spacing:1px; font-weight:600; margin-bottom:9px; } .room-title { font-size:20px; margin:0 0 5px; letter-spacing:-.4px; }
  .room-list { display:flex; flex-wrap:wrap; gap:6px; padding:16px 20px; background:var(--surface); border-top:1px solid var(--line); } .room-list button { min-height:32px; font-size:11px; padding:6px 10px; font-weight:500; } .room-list button.active { background:#eaf4ee; color:var(--accent); border-color:#b2d4c1; }
  .section { margin-top:21px; padding-top:18px; border-top:1px solid var(--line); } .sensor-reading { display:flex; align-items:center; justify-content:space-between; gap:10px; margin:9px 0; padding:11px 12px; border:1px solid var(--line); border-radius:9px; background:var(--soft); }
  .sensor-reading .sensor-name { font-size:11px; overflow-wrap:anywhere; display:block; } .sensor-reading strong { font-size:18px; color:var(--accent); white-space:nowrap; font-weight:600; } .sensor-reading strong.status { font-size:11px; color:var(--muted); white-space:normal; text-align:right; } .sensor-id { font-size:10px; color:var(--muted); }
  label { display:block; color:var(--ink); font-size:12px; font-weight:500; } label>span { display:block; margin-bottom:6px; } input:not([type=checkbox]):not([type=file]),select,textarea { width:100%; border:1px solid #cbd9cf; border-radius:8px; background:var(--surface); color:var(--ink); padding:10px 11px; font-size:12px; min-height:39px; }
  input[type=checkbox] { accent-color:var(--accent); width:15px; height:15px; flex:none; } .sensor-select { max-height:200px; overflow-y:auto; display:grid; gap:6px; margin-top:9px; } .sensor-select label { display:flex; align-items:center; gap:8px; padding:7px 0; font-weight:400; } .sensor-select span { margin:0; font-size:11px; overflow-wrap:anywhere; }
  .setup { padding:22px 26px; border-top:1px solid var(--line); background:#fafcf9; } .steps { display:grid; grid-template-columns:minmax(0,1fr) minmax(0,1fr); gap:24px; } .step { min-width:0; } .step-heading { display:flex; align-items:center; gap:9px; margin:0 0 14px; } .step-number { width:22px; height:22px; display:grid; place-items:center; border-radius:7px; font-size:11px; font-weight:600; color:var(--accent); background:#e3eee6; } .step-heading h2 { margin:0; font-size:13px; }
  .field-row { display:grid; grid-template-columns:1fr 1fr; gap:10px; margin:12px 0; } .field { margin:12px 0; } code { font-family:ui-monospace,monospace; font-size:11px; overflow-wrap:anywhere; } textarea.json { height:124px; resize:vertical; font-family:ui-monospace,monospace; font-size:11px; line-height:1.5; margin:10px 0; } .hint { font-size:11px; color:var(--muted); line-height:1.55; }
  .empty { min-height:280px; display:flex; flex-direction:column; align-items:center; justify-content:center; text-align:center; padding:34px; background:#f4f8f3; border-top:1px solid var(--line); } .empty-symbol { color:#5d8f78; width:59px; height:59px; display:grid; place-items:center; background:#e7f0e7; border-radius:18px; margin-bottom:18px; } .empty-symbol svg { width:30px; height:30px; } .empty h2 { font-size:18px; } .empty p { max-width:420px; font-size:12px; color:var(--muted); }
  .footer { padding:13px 26px; border-top:1px solid var(--line); display:flex; gap:15px; align-items:center; justify-content:space-between; font-size:10px; color:var(--muted); } .footer span { line-height:1.5; }
  .edit-note { color:#775c24; font-size:11px; line-height:1.5; margin-top:10px; } .points { display:grid; gap:6px; margin-top:10px; max-height:240px; overflow-y:auto; } .point { display:grid; grid-template-columns:18px 1fr 1fr 30px 30px; align-items:center; gap:4px; font-size:10px; } .point input { padding:6px!important; min-height:30px!important; min-width:0; } .point button { min-height:30px; padding:3px; }
  .dialog-backdrop { position:fixed; inset:0; z-index:1000; background:#112a2370; display:flex; align-items:center; justify-content:center; padding:20px; } .dialog { width:min(760px,100%); max-height:90vh; overflow:auto; padding:25px; border-radius:17px; background:var(--surface); box-shadow:0 20px 70px #00150f40; } .dialog-top { display:flex; justify-content:space-between; align-items:start; gap:15px; } .dialog h2 { font-size:20px; margin:0 0 8px; } .dialog textarea { height:43vh; resize:vertical; font-family:ui-monospace,monospace; font-size:11px; line-height:1.6; margin:15px 0; } .dialog .notice { margin:12px 0; } .dialog-actions { display:flex; justify-content:flex-end; gap:8px; margin-top:14px; flex-wrap:wrap; } .removed { padding:10px 13px; background:var(--soft); border-radius:8px; font-size:12px; line-height:1.6; max-height:240px; overflow:auto; }
  .removed-sensor { display:block; overflow-wrap:anywhere; } .empty-floor { padding:0 15px 12px; }
  @media(max-width:740px) { header { padding:18px; } h1 { font-size:18px; } .brand-icon { width:37px; height:37px; } .toolbar { padding:13px 18px; flex-wrap:wrap; } .content { grid-template-columns:1fr; } aside { border-left:0; border-top:1px solid var(--line); padding:20px; } .steps { grid-template-columns:1fr; gap:24px; } .setup { padding:20px 18px; } .notice { margin-left:18px; margin-right:18px; } .footer { padding:13px 18px; } .plan-area { padding:15px; } .badge { display:none; } .dialog-backdrop { padding:10px; } .dialog { padding:19px; } .dialog textarea { height:40vh; } }
  :host { --accent:var(--primary-color,#0277bd); }
  .dialog { color:var(--ink); background:var(--surface); border-radius:var(--ha-card-border-radius,12px); }
  .dialog button.primary { background:var(--primary-color,#0277bd); border-color:var(--primary-color,#0277bd); color:var(--text-primary-color,#fff); }
  .dialog button.danger { color:var(--error-color,#db4437); }
  .dialog input,.dialog select,.dialog textarea { background:var(--surface); color:var(--ink); border-color:var(--line); min-height:44px; font-size:14px; }
  .dialog .notice { color:var(--ink); background:var(--soft); border-color:var(--line); }
  .dialog :focus-visible { outline-color:var(--primary-color,#0277bd); }
  .dialog button { min-height:44px; }
  :host { --soft:var(--secondary-background-color,#f3f7f4); --line:var(--divider-color,#dce6df); } .plan-area,.empty,.setup { background:var(--secondary-background-color,#f3f6f2); }
`;
